# Generated by Django 4.2.28 on 2026-02-09 16:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('clerk', 'Clerk/Staff'), ('librarian', 'Library/Research Officer'), ('mp', 'Member of Parliament'), ('public', 'Public User')], default='public', max_length=20, verbose_name='User Role')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('library_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Library Card Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('can_upload', models.BooleanField(default=False, verbose_name='Can Upload Documents')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Can Delete Documents')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Can Manage Users')),
                ('can_view_all_documents', models.BooleanField(default=False, verbose_name='Can View All Documents')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Password Last Changed')),
                ('account_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Account Expiration Date')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'permissions': [('view_audit_log', 'Can view audit logs'), ('export_documents', 'Can export documents'), ('bulk_upload', 'Can bulk upload documents')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
