# Generated by Django 4.2.28 on 2026-02-09 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Document Title')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='URL Slug')),
                ('document_type', models.CharField(choices=[('act', 'Act of Parliament'), ('bill', 'Bill'), ('amendment', 'Amendment'), ('hansard', 'Hansard'), ('committee_report', 'Committee Report'), ('journal', 'Parliamentary Journal'), ('gazette', 'Gazette'), ('research', 'Research Document'), ('contract', 'Contract/Agreement'), ('policy', 'Policy Document'), ('other', 'Other')], default='other', max_length=50, verbose_name='Document Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=500, verbose_name='Keywords')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'tiff', 'tif', 'xml', 'json'])], verbose_name='Document File')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='File Hash (SHA-256)')),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100, verbose_name='MIME Type')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('version_notes', models.TextField(blank=True, verbose_name='Version Notes')),
                ('act_number', models.CharField(blank=True, max_length=50, verbose_name='Act Number')),
                ('bill_number', models.CharField(blank=True, max_length=50, verbose_name='Bill Number')),
                ('session', models.CharField(blank=True, max_length=50, verbose_name='Parliamentary Session')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='Year')),
                ('date_enacted', models.DateField(blank=True, null=True, verbose_name='Date Enacted/Published')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('committee_name', models.CharField(blank=True, max_length=200, verbose_name='Committee Name')),
                ('report_number', models.CharField(blank=True, max_length=50, verbose_name='Report Number')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('confidential', 'Confidential'), ('classified', 'Classified')], default='public', max_length=20, verbose_name='Access Level')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Pages')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'permissions': [('view_restricted', 'Can view restricted documents'), ('view_confidential', 'Can view confidential documents'), ('view_classified', 'Can view classified documents'), ('approve_document', 'Can approve documents for publication'), ('bulk_upload', 'Can bulk upload documents'), ('export_document', 'Can export documents')],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='file-text', max_length=50, verbose_name='Icon Class')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color Code')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Version Number')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, verbose_name='Version File')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('changes', models.TextField(blank=True, verbose_name='Change Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('print', 'Print'), ('share', 'Share'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=20, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.TextField(blank=True, verbose_name='Additional Details')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document', verbose_name='Document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'year'], name='documents_d_documen_44393b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['access_level', 'is_published'], name='documents_d_access__743dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='documents_d_uploade_28af31_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title', 'slug'], name='documents_d_title_920bed_idx'),
        ),
    ]
