# Generated by Django 4.2.28 on 2026-02-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_billstage_committee_speech_question_ordinance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('introduced', 'Introduced'), ('under_review', 'Under Review'), ('passed', 'Passed'), ('assented', 'Assented by President'), ('act', 'Enacted as Act'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('lapsed', 'Lapsed')], max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('act', 'Act of Parliament'), ('bill', 'Bill'), ('amendment', 'Amendment'), ('hansard', 'Hansard'), ('committee_report', 'Committee Report'), ('journal', 'Parliamentary Journal'), ('gazette', 'Gazette'), ('research', 'Research Document'), ('contract', 'Contract/Agreement'), ('policy', 'Policy Document'), ('book', 'Book'), ('other', 'Other')], default='other', max_length=50, verbose_name='Document Type'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300, verbose_name='Author(s)')),
                ('co_authors', models.CharField(blank=True, max_length=500, verbose_name='Co-Author(s)')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('publisher', models.CharField(max_length=200, verbose_name='Publisher')),
                ('publication_place', models.CharField(blank=True, max_length=100, verbose_name='Publication Place')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Publication Year')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='Edition')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Volume')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Pages')),
                ('genre', models.CharField(choices=[('constitutional_law', 'Constitutional Law'), ('parliamentary_procedure', 'Parliamentary Procedure'), ('legislative_studies', 'Legislative Studies'), ('public_policy', 'Public Policy'), ('governance', 'Governance'), ('democracy', 'Democracy & Elections'), ('biography', 'Biography/Memoir'), ('history', 'History'), ('reference', 'Reference'), ('other', 'Other')], default='other', max_length=30, verbose_name='Genre/Category')),
                ('language', models.CharField(default='en', max_length=20, verbose_name='Language')),
                ('binding', models.CharField(blank=True, help_text='e.g., Hardcover, Paperback', max_length=50, verbose_name='Binding Type')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='Dimensions')),
                ('accession_number', models.CharField(max_length=50, unique=True, verbose_name='Accession Number')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Acquisition Date')),
                ('acquisition_source', models.CharField(blank=True, max_length=200, verbose_name='Acquisition Source')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost')),
                ('catalog_date', models.DateField(auto_now_add=True, verbose_name='Catalog Date')),
                ('shelf_location', models.CharField(blank=True, max_length=100, verbose_name='Shelf Location')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Barcode')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Borrowing')),
                ('is_reference_only', models.BooleanField(default=False, verbose_name='Reference Only')),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='new', max_length=50, verbose_name='Condition')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='documents.document', verbose_name='Associated Document')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['author', 'publication_year'],
                'permissions': [('manage_books', 'Can manage library books')],
            },
        ),
    ]
