# Generated by Django 4.2.28 on 2026-02-11 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Constituency Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Constituency Code')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population')),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area (sq km)')),
                ('voters_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Registered Voters')),
                ('capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital/Town')),
                ('map_coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='Map Coordinates')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Constituency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Constituency',
                'verbose_name_plural': 'Constituencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True, verbose_name='Place of Birth')),
                ('constituency', models.CharField(max_length=200, verbose_name='Constituency')),
                ('constituency_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Constituency Code')),
                ('party', models.CharField(blank=True, max_length=100, null=True, verbose_name='Political Party')),
                ('party_abbreviation', models.CharField(blank=True, max_length=10, null=True, verbose_name='Party Abbreviation')),
                ('speaker', models.CharField(blank=True, max_length=100, null=True, verbose_name='Speaker/Position')),
                ('is_speaker', models.BooleanField(default=False, verbose_name='Is Speaker/Deputy Speaker')),
                ('committees', models.TextField(blank=True, help_text='List of committees the member belongs to', null=True, verbose_name='Committee Memberships')),
                ('committee_chair', models.TextField(blank=True, null=True, verbose_name='Committee Chair Positions')),
                ('first_elected', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2100)], verbose_name='First Elected Year')),
                ('term_start', models.DateField(blank=True, null=True, verbose_name='Current Term Start')),
                ('term_end', models.DateField(blank=True, null=True, verbose_name='Current Term End')),
                ('parliament_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parliament Number')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Educational Background')),
                ('profession', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession/Occupation')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('office_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Office Location')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Profile')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Profile')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Personal Website')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Notable Achievements')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Member')),
                ('is_retired', models.BooleanField(default=False, verbose_name='Retired Member')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member of Parliament',
                'verbose_name_plural': 'Members of Parliament',
                'ordering': ['name'],
                'permissions': [('view_member_details', 'Can view member details'), ('export_member_data', 'Can export member data')],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Party Name')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Abbreviation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parties/logos/', verbose_name='Party Logo')),
                ('color', models.CharField(default='#000000', help_text='Hex color code for party branding', max_length=7, verbose_name='Party Color')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)], verbose_name='Founded Year')),
                ('ideology', models.CharField(blank=True, max_length=200, null=True, verbose_name='Political Ideology')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Party Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Party')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Political Party',
                'verbose_name_plural': 'Political Parties',
                'ordering': ['name'],
            },
        ),
    ]
