"""
Data migration to add correct National Assembly members 2022-2027.
Uses direct Django ORM to avoid migration state issues.
"""

from django.db import migrations
from django.utils.text import slugify


def add_gambia_national_assembly_members(apps, schema_editor):
    """Add correct parliamentary members for The Gambia 2022-2027."""
    # Import directly to avoid historical model issues
    from members.models import Member, Party, Constituency
    
    # Create or update parties
    parties_data = [
        {'abbreviation': 'UDP', 'name': 'United Democratic Party', 'color': '#ce1126', 'founded_year': 1997, 'ideology': 'Centrism, Liberalism'},
        {'abbreviation': 'NPP', 'name': 'National People\'s Party', 'color': '#3c8d2f', 'founded_year': 2019, 'ideology': 'Populism'},
        {'abbreviation': 'Independent', 'name': 'Independent', 'color': '#6c757d'},
        {'abbreviation': 'NRP', 'name': 'National Reconciliation Party', 'color': '#f0ad4e', 'founded_year': 2012},
        {'abbreviation': 'PDOIS', 'name': 'People\'s Democratic Organisation for Independence and Socialism', 'color': '#d63384', 'founded_year': 1981},
        {'abbreviation': 'APRC', 'name': 'Alliance for Patriotic Reorientation and Construction', 'color': '#0d6efd', 'founded_year': 1996},
        {'abbreviation': 'Nominated', 'name': 'Nominated Member', 'color': '#20c997'},
    ]
    
    for party_data in parties_data:
        party, created = Party.objects.get_or_create(
            abbreviation=party_data['abbreviation'],
            defaults=party_data
        )
        if not created:
            # Update existing party
            for key, value in party_data.items():
                setattr(party, key, value)
            party.save()
    
    # Create constituencies
    constituencies_data = [
        {'code': 'BAN', 'name': 'Banjul', 'region': 'Banjul'},
        {'code': 'BAN-N', 'name': 'Banjul North', 'region': 'Banjul'},
        {'code': 'BAN-C', 'name': 'Banjul Central', 'region': 'Banjul'},
        {'code': 'BAN-S', 'name': 'Banjul South', 'region': 'Banjul'},
        {'code': 'KAN', 'name': 'Kanifing', 'region': 'Kanifing'},
        {'code': 'SER', 'name': 'Serekunda', 'region': 'Kanifing'},
        {'code': 'SER-W', 'name': 'Serekunda West', 'region': 'Kanifing'},
        {'code': 'KOM-S', 'name': 'Kombo South', 'region': 'West Coast'},
        {'code': 'KOM-E', 'name': 'Kombo East', 'region': 'West Coast'},
        {'code': 'BRI-N', 'name': 'Brikama North', 'region': 'West Coast'},
        {'code': 'BRI-S', 'name': 'Brikama South', 'region': 'West Coast'},
        {'code': 'KUN', 'name': 'Kuntaur', 'region': 'Central River'},
        {'code': 'J-B', 'name': 'Janjanbureh', 'region': 'Central River'},
        {'code': 'L-B', 'name': 'Lower Baddibu', 'region': 'North Bank'},
        {'code': 'U-B', 'name': 'Upper Baddibu', 'region': 'North Bank'},
        {'code': 'W-E', 'name': 'Wuli East', 'region': 'Upper River'},
        {'code': 'W-W', 'name': 'Wuli West', 'region': 'Upper River'},
        {'code': 'KAN-C', 'name': 'Kiang Central', 'region': 'Lower River'},
        {'code': 'KAN-E', 'name': 'Kiang East', 'region': 'Lower River'},
        {'code': 'KAN-W', 'name': 'Kiang West', 'region': 'Lower River'},
        {'code': 'JAR-W', 'name': 'Jarra West', 'region': 'Lower River'},
        {'code': 'JAR-E', 'name': 'Jarra East', 'region': 'Lower River'},
        {'code': 'JAR-C', 'name': 'Jarra Central', 'region': 'Lower River'},
        {'code': 'FONI', 'name': 'Foni', 'region': 'Western Division'},
        {'code': 'FONI-B', 'name': 'Foni Bintang', 'region': 'Western Division'},
        {'code': 'FONI-BKS', 'name': 'Foni B. K. S', 'region': 'Western Division'},
        {'code': 'FONI-BRF', 'name': 'Foni Brefet', 'region': 'Western Division'},
        {'code': 'FONI-JR', 'name': 'Foni Jarrol', 'region': 'Western Division'},
        {'code': 'FONI-BND', 'name': 'Foni Bondali', 'region': 'Western Division'},
        {'code': 'KNT', 'name': 'Kantora', 'region': 'Upper River'},
        {'code': 'TUM', 'name': 'Tumana', 'region': 'Upper River'},
        {'code': 'JESH', 'name': 'Jeshwang', 'region': 'Kanifing'},
        {'code': 'LAT', 'name': 'Latrikunda', 'region': 'Kanifing'},
        {'code': 'BKA', 'name': 'Bakau', 'region': 'Kanifing'},
        {'code': 'BUN', 'name': 'Bundrumka Kunda', 'region': 'Upper River'},
        {'code': 'BUS', 'name': 'Busumbala', 'region': 'Kanifing'},
        {'code': 'SAB', 'name': 'Sanjal', 'region': 'North Bank'},
        {'code': 'JAM', 'name': 'Jamaica', 'region': 'West Coast'},
        {'code': 'JOK', 'name': 'Jokadu', 'region': 'North Bank'},
        {'code': 'KOM-C', 'name': 'Kombo Central', 'region': 'West Coast'},
        {'code': 'JARA', 'name': 'Jarra', 'region': 'Lower River'},
        {'code': 'JIM', 'name': 'Jimara', 'region': 'Upper River'},
        {'code': 'K-B', 'name': 'Kombo B', 'region': 'West Coast'},
        {'code': 'L-FW', 'name': 'Lower Fulladu West', 'region': 'Central River'},
        {'code': 'U-FW', 'name': 'Upper Fulladu West', 'region': 'Central River'},
        {'code': 'L-NI', 'name': 'Lower Niumi', 'region': 'North Bank'},
        {'code': 'U-NI', 'name': 'Upper Niumi', 'region': 'North Bank'},
        {'code': 'SAL-L', 'name': 'Lower Saloum', 'region': 'Upper River'},
        {'code': 'SAL-U', 'name': 'Upper Saloum', 'region': 'Upper River'},
        {'code': 'NIA', 'name': 'Nianija', 'region': 'Central River'},
        {'code': 'NIAN', 'name': 'Niani', 'region': 'Central River'},
        {'code': 'NIAN-E', 'name': 'Niamina East', 'region': 'Central River'},
        {'code': 'NIAN-W', 'name': 'Niamina West', 'region': 'Central River'},
        {'code': 'DANK', 'name': 'Dankunku', 'region': 'Central River'},
        {'code': 'ILL', 'name': 'Illiassa', 'region': 'North Bank'},
        {'code': 'NIA-C', 'name': 'Nianija', 'region': 'Central River'},
    ]
    
    for const_data in constituencies_data:
        const, created = Constituency.objects.get_or_create(
            code=const_data['code'],
            defaults={**const_data, 'is_active': True}
        )
        if not created:
            for key, value in const_data.items():
                setattr(const, key, value)
            const.is_active = True
            const.save()
    
    # Members data - 2022-2027
    members_data = [
        {
            'name': 'Badjie Musa Tallinding Kunjang',
            'constituency': 'Tallinding Kunjang',
            'constituency_code': 'TKG',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Badjie Bakary K. Foni Bintang',
            'constituency': 'Foni Bintang',
            'constituency_code': 'FONI-B',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Baldeh Alieu Jarra West',
            'constituency': 'Jarra West',
            'constituency_code': 'JAR-W',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Bah Modou Lamin B. Banjul North',
            'constituency': 'Banjul North',
            'constituency_code': 'BAN-N',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Bah Saikou Basse',
            'constituency': 'Basse',
            'constituency_code': 'BAS',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Bah Yunusa N. Kiang Central',
            'constituency': 'Kiang Central',
            'constituency_code': 'KAN-C',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Barry Haruna Jarra East',
            'constituency': 'Jarra East',
            'constituency_code': 'JAR-E',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Barrow Kebba K. Kombo South',
            'constituency': 'Kombo South',
            'constituency_code': 'KOM-S',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Camara Amadou Nianija',
            'constituency': 'Nianija',
            'constituency_code': 'NIA',
            'party': 'National Reconciliation Party',
            'party_abbreviation': 'NRP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Ceesay Abdoulie Old Yundum',
            'constituency': 'Old Yundum',
            'constituency_code': 'YND-O',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Ceesay Madi MK Serekunda West',
            'constituency': 'Serekunda West',
            'constituency_code': 'SER-W',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Ceesay Alfusainey',
            'constituency': 'Serekunda',
            'constituency_code': 'SER',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Ceesay Lamin Kiang West',
            'constituency': 'Kiang West',
            'constituency_code': 'KAN-W',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Ceesay Maimuna',
            'constituency': 'Nominated',
            'constituency_code': 'NOM',
            'party': 'Nominated Member',
            'party_abbreviation': 'Nominated',
            'gender': 'female',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Ceesay Alh. Babou Sabach Sanjal',
            'constituency': 'Sanjal',
            'constituency_code': 'SAB',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Conteh Essa Jimara',
            'constituency': 'Jimara',
            'constituency_code': 'JIM',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Cham Fatou Sanimentereng',
            'constituency': 'Sanimentereng',
            'constituency_code': 'SAN',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'female',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Cham Musa Serrekunda',
            'constituency': 'Serrekunda',
            'constituency_code': 'SER',
            'party': 'People\'s Democratic Organisation for Independence and Socialism',
            'party_abbreviation': 'PDOIS',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Cham Tamsir Lower Niumi',
            'constituency': 'Lower Niumi',
            'constituency_code': 'L-NI',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Colley Amie Foni Brefet',
            'constituency': 'Foni Brefet',
            'constituency_code': 'FONI-BRF',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'female',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Dampha Sankung Illiassa',
            'constituency': 'Illiassa',
            'constituency_code': 'ILL',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Darbo Alhagie S. Brikama North',
            'constituency': 'Brikama North',
            'constituency_code': 'BRI-N',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Darboe Omar Upper Niumi',
            'constituency': 'Upper Niumi',
            'constituency_code': 'U-NI',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Fofana Kebba Lang',
            'constituency': 'Nominated',
            'constituency_code': 'NOM',
            'party': 'Nominated Member',
            'party_abbreviation': 'Nominated',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Gassama Kemo Lower Baddibu',
            'constituency': 'Lower Baddibu',
            'constituency_code': 'L-B',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Gibba Almameh Foni Kansala',
            'constituency': 'Foni Kansala',
            'constituency_code': 'FONI-K',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Gassama Yaya Kiang East',
            'constituency': 'Kiang East',
            'constituency_code': 'KAN-E',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jaiteh Ebrima Sandu',
            'constituency': 'Sandu',
            'constituency_code': 'SAN',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jammeh Omar Janjanbureh',
            'constituency': 'Janjanbureh',
            'constituency_code': 'J-B',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jammeh Sulayman Bundungka Kunda',
            'constituency': 'Bundrumka Kunda',
            'constituency_code': 'BUN',
            'party': 'Alliance for Patriotic Reorientation and Construction',
            'party_abbreviation': 'APRC',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jatta Fabakary Tombong',
            'constituency': 'Nominated',
            'constituency_code': 'NOM',
            'party': 'Nominated Member',
            'party_abbreviation': 'Nominated',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_speaker': True,
            'speaker': 'Speaker of the National Assembly',
            'is_active': True,
        },
        {
            'name': 'Jallow Samba Niamina Dankunku',
            'constituency': 'Dankunku',
            'constituency_code': 'DANK',
            'party': 'National Reconciliation Party',
            'party_abbreviation': 'NRP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jallow Kebba Jarra Central',
            'constituency': 'Jarra Central',
            'constituency_code': 'JAR-C',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jawara Fatou K.',
            'constituency': 'Nominated',
            'constituency_code': 'NOM',
            'party': 'Nominated Member',
            'party_abbreviation': 'Nominated',
            'gender': 'female',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jawara Sainey Lower Saloum',
            'constituency': 'Lower Saloum',
            'constituency_code': 'SAL-L',
            'party': 'National Reconciliation Party',
            'party_abbreviation': 'NRP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jawo Salifu Jokadu',
            'constituency': 'Jokadu',
            'constituency_code': 'JOK',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jeng Dawda Niamina East',
            'constituency': 'Niamina East',
            'constituency_code': 'NIAN-E',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Jobe Omar Niani',
            'constituency': 'Niani',
            'constituency_code': 'NIAN',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Kanteh Muhamed Busumbala',
            'constituency': 'Busumbala',
            'constituency_code': 'BUS',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Kora Bakary Upper Fulladu West',
            'constituency': 'Upper Fulladu West',
            'constituency_code': 'U-FW',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Kora Nfally M. Tumana',
            'constituency': 'Tumana',
            'constituency_code': 'TUM',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Mballow Gibbi Lower Fulladu West',
            'constituency': 'Lower Fulladu West',
            'constituency_code': 'L-FW',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Mbow Alhagie Upper Saloum',
            'constituency': 'Upper Saloum',
            'constituency_code': 'SAL-U',
            'party': 'National Reconciliation Party',
            'party_abbreviation': 'NRP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Njai Abdoulie Banjul Central',
            'constituency': 'Banjul Central',
            'constituency_code': 'BAN-C',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Njai Fatoumatta Banjul South',
            'constituency': 'Banjul South',
            'constituency_code': 'BAN-S',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'female',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Njie Seedy SK',
            'constituency': 'Nominated',
            'constituency_code': 'NOM',
            'party': 'Nominated Member',
            'party_abbreviation': 'Nominated',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_speaker': True,
            'speaker': 'Deputy Speaker',
            'is_active': True,
        },
        {
            'name': 'Sabally Nfamara Wuli West',
            'constituency': 'Wuli West',
            'constituency_code': 'W-W',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Saho Sulayman Central Baddibu',
            'constituency': 'Central Baddibu',
            'constituency_code': 'C-B',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Sanneh Kebba T. Foni Jarrol',
            'constituency': 'Foni Jarrol',
            'constituency_code': 'FONI-JR',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Sanneh Lamin J. Brikama South',
            'constituency': 'Brikama South',
            'constituency_code': 'BRI-S',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Sanneh Pa Dembo Foni Bondali',
            'constituency': 'Foni Bondali',
            'constituency_code': 'FONI-BND',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Sanyang Yahya Latrikunda Sabiji',
            'constituency': 'Latrikunda Sabiji',
            'constituency_code': 'LAT',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Sarr Sheriff Jeshwang',
            'constituency': 'Jeshwang',
            'constituency_code': 'JESH',
            'party': 'Alliance for Patriotic Reorientation and Construction',
            'party_abbreviation': 'APRC',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Sowe Abdou Kombo East',
            'constituency': 'Kombo East',
            'constituency_code': 'KOM-E',
            'party': 'Independent',
            'party_abbreviation': 'Independent',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Sowe Birom Niamina West',
            'constituency': 'Niamina West',
            'constituency_code': 'NIAN-W',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Touray Assan Bakau',
            'constituency': 'Bakau',
            'constituency_code': 'BKA',
            'party': 'United Democratic Party',
            'party_abbreviation': 'UDP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Touray Suwaibou Wuli East',
            'constituency': 'Wuli East',
            'constituency_code': 'W-E',
            'party': 'People\'s Democratic Organisation for Independence and Socialism',
            'party_abbreviation': 'PDOIS',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
        {
            'name': 'Tunkara Billay G. Kantora',
            'constituency': 'Kantora',
            'constituency_code': 'KNT',
            'party': 'National People\'s Party',
            'party_abbreviation': 'NPP',
            'gender': 'male',
            'first_elected': 2022,
            'parliament_number': 6,
            'is_active': True,
        },
    ]
    
    # Clear existing members and add new ones
    Member.objects.all().delete()
    
    for idx, data in enumerate(members_data, 1):
        data['slug'] = slugify(data['name'])
        data['sort_order'] = idx
        Member.objects.create(**data)


def remove_members(apps, schema_editor):
    """Remove all members (for rollback)."""
    from members.models import Member, Party, Constituency
    
    Member.objects.all().delete()
    Party.objects.filter(abbreviation__in=['UDP', 'NPP', 'Independent', 'NRP', 'PDOIS', 'APRC', 'Nominated']).delete()
    Constituency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_sample_data'),
    ]

    operations = [
        migrations.RunPython(add_gambia_national_assembly_members, remove_members),
    ]

